# Generated by Django 4.1.3 on 2022-12-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_signup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='image',
            field=models.ImageField(default='img19_1920x1200.jpg', upload_to=''),
        ),
    ]
