# Generated by Django 4.1.3 on 2022-12-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_dob_signup_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='Passwords',
            field=models.CharField(default=0, max_length=100000000000000),
            preserve_default=False,
        ),
    ]
