# Generated by Django 4.1.3 on 2022-12-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_signup_passwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Passwords',
            field=models.CharField(default='{"website":"password"}', max_length=100000000000000),
        ),
    ]
