# Generated by Django 4.1.3 on 2022-12-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_signup_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='Passwords',
            field=models.CharField(default='{"website":"password"}', max_length=500000),
        ),
    ]
