# Generated by Django 4.1.3 on 2022-12-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_signup_passwords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='Passwords',
        ),
    ]
