# Generated by Django 4.1.3 on 2022-12-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_signup_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='passwords',
            field=models.CharField(default="{'website':'password'}", max_length=10000000),
        ),
    ]
