# Generated by Django 4.1.3 on 2023-02-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_signup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='passwords',
            field=models.CharField(default='cSNYUmE677m3C77+k6ltnucqkJMZbeOxo2cb74W5xCXBVGOXS2/t5jGxs0aHv216EvPFjXQt76tQ3UWIJjV5vEMn8FpGP43wYEg+2cLdD6PYTldXcBgiw6/UhhUe74RW74Gze9kX4PRxfihu4kZaePxOZXZJLRfZFoQmr6x+N7ir2+kye7v5+s3d2H1PA8F2', max_length=10000000),
        ),
    ]
